fix: include windows.h instead of child headers
Fixed this:
  C:\Program Files (x86)\Windows Kits\10\include\...\um\winnt.h(173): fatal error C1189: #error:  "No Target Architecture"

Wikipedia said:
> Many of these files cannot simply be included by themselves (they are
  not self-contained), because of dependencies.

About "WIN32_LEAN_AND_MEAN":
  https://docs.microsoft.com/en-us/windows/win32/winprog/using-the-windows-headers#faster-builds-with-smaller-header-files